version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    restart: unless-stopped

  users_microservice:
    build: ./users_microservice
    ports:
      - "8001:8001"
    restart: unless-stopped

  orders_microservice:
    build: ./orders_microservice
    ports:
      - "8002:8002"
    restart: unless-stopped