version: '3.8'

services:
  users_microservice:
    build: ./users_microservice
    ports:
      - "8000:8000"
    restart: unless-stopped

  orders_microservice:
    build: ./orders_microservice
    ports:
      - "8001:8001"
    restart: unless-stopped